name: Conventional PR

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  conventional-pr:
    uses: ./.github/workflows/reusable-conventional-pr.yml
