name: Labeler

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-check:
    uses: ./.github/workflows/reusable-pr-check.yml
