name: Release

on:
  push:
    branches: [main]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: Songmu/tagpr@b3fb89424646b06c8aa460f50307c60b6a541425 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
